[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bp_analysis"
dynamic = ["version"]
dependencies = [
	"astropy >= 5.0",
	"ipywidgets >= 8.0",
	"matplotlib >= 3.6",
	"numba",
	"numpy >= 1.21",
	"reproject >= 0.13",
	"scipy >= 1.8",
	"tqdm >= 4.66",
]
requires-python = ">= 3.11"
authors = [
	{name="Sam Van Kooten"},
]

description = "Python code for analyzing bright points in DKIST images"
readme = "README.md"

[project.optional-dependencies]
test = [
	"pytest >= 8.0",
	"pytest-arraydiff >= 0.6",
	"pytest-mock >= 3.7",
	"pytest-mpl >= 0.16",
]

[tool.setuptools.dynamic]
version = {attr = "bp_analysis.__version__"}
