GOOD = 'good'
FALSE_POS = 'fpos'
CLOSE_NEIGHBOR = 'neighbor'
EDGE = 'edge'
TOO_SMALL = 'too small'
TOO_BIG = 'too big'

NORMAL = 'normal'
MERGE = 'merge'
SPLIT = 'split'
FIRST_IMAGE = 'first_image'
LAST_IMAGE = 'last_image'
COMPLEX = 'complex'